CREATE TABLE IF NOT EXISTS `machine` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(256) NOT NULL COMMENT '机器名',
    `launch_date` INT NOT NULL COMMENT '启动时间'
) ENGINE = InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb4;